### PR TITLE
dont pirate convert: fix https://github.com/mauro3/Parameters.jl/issues/73

### PR DESCRIPTION
**Pull request by piever**

### CODE REVIEW

**Comment by cstjean** [comment]
I've been using this branch, and it fixed my issues. Any reason not to merge?

**Comment by piever** [comment]
Somehow I'm not sure that `ShiftedArrays.convert(Array, v)` is the best interface to convert a vector of N dimensional `ShiftedArray` into a `N+1` dimensional `Array`. Do you have any suggestions on the API?

**Comment by cstjean** [comment]
`array_from(vec_of_shifted_arrays)`? I agree that `convert` is not super appropriate.

**Comment by piever** [comment]
You're right that this is not quite a conversion. I'll add some dedicated helper functions name and merge.

**Pull request merged**
